import Image from "next/image";
import Link from "next/link";

import modclave from "@/public/projects/modclaveHero.jpg";
import module_closeup from "./module_closeup.jpg";
import autoclave_requirements from "./autoclave_requirements.png";
import instruments_stockphoto from "./ibrahim-boran-pV5arhEZHiA-unsplash.jpg";

import Header from "@/components/header";

import "@/styles/project.css";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between px-2 lg:px-4 py-12 lg:py-24">
      <div className="max-w-3xl w-full flex flex-col gap-16 lg:gap-24 leading-loose">
        <Header />
        <div className="flex flex-col gap-2">
          <h1 className="left-0">modClave: Store & Sterilise</h1>
          <p className="text-md lg:text-xl font-light text-slate-500">An affordable and compact sterilisation device that addresses waste mismanagement in healthcare by enabling clinics to reprocess instruments, promoting sustainability and emphasizing the importance of waste reduction during product development.</p>

        </div>

        <div className="flex flex-col">
          <div className="flex justify-between px-4 bg-slate-50 p-4 text-sm">
            <span>Queensland University of Technology</span>
            <span>2022</span>
          </div>

          <p className="bg-slate-100 p-4 text-sm leading-relaxed">
            This project was completed over 12-months in the final year of my Industrial Design degree as my disertation project. The projects outcome incluced a reserach thesis and a developed product based on the reserach completed in the first 6 months of the project.
          </p>
        </div>


        <Image
          alt="hero image of the modclave"
          src={modclave}
          sizes="(min-width: 808px) 50vw, 100vw"
          className='off-width'
          placeholder="blur"
        />

        <div className='section'>
          <h3>Introduction</h3>
          <p className="leading-loose">
            The modClave, a module-based steam sterilisation desktop appliance, is
            a groundbreaking solution that addresses the issues of waste
            mismanagement and sustainability in the healthcare industry. Developed
            through extensive research involving healthcare professionals in
            south-east Queensland, the modClave tackles the prevalent problem of
            excessive waste generated by poor waste practices.
          </p>
        </div>


        <div className="section items-center">
          <Image
            alt="hero image of the modclave"
            src={instruments_stockphoto}
            sizes="(min-width: 808px) 50vw, 100vw"
            placeholder="blur"
          />
          <p className=" text-xs font-light text-slate-500 max-w-md leading-loose">
            Example of single-use instruments that are often used once and disposed of in medical practices. (<Link href='https://unsplash.com/photos/pV5arhEZHiA' target="_blank">source: Ibrahim Boran, Unsplash</Link>)
          </p>
        </div>


        <div className='section'>
          <h3>Problem</h3>
          <p className="leading-loose">
            While healthcare professionals express their intentions to be
            sustainable, the reality is that the industry heavily relies on a
            pay-per-use model, resulting in the disposal of large volumes of
            single-use instruments. This wasteful approach is particularly
            prominent in smaller practices, where sustainable alternatives are
            deemed too expensive and time-consuming, exacerbating the issue of
            excess waste.
          </p>
        </div>


        <div className='grid grid-cols-1 xl:grid-cols-2 gap-12 off-width items-center bg-slate-50 px-4 lg:px-8 py-6 lg:py-12'>
          <div className="flex flex-col items-center">
            <Image
              alt="example of a room layout with a traditional autoclave"
              src={autoclave_requirements}
              sizes="(min-width: 800px) 50vw, 100vw"
              placeholder="blur"
            />
            <p className=" text-xs font-light text-slate-500 max-w-md leading-loose">
              Extracted from Infection prevention and control standards: for general practices and other office-based and community-based practices (RACGP, 2014)
            </p>
          </div>
          <p className="leading-loose">
            Traditionally, autoclaves have been the gold standard for
            sterilisation in the medical industry. However, their high cost, space
            requirements, and inefficiency for smaller practices have limited
            their accessibility and effectiveness. The modClave revolutionises
            waste management practices by providing an affordable and compact
            solution for clinics that are currently priced out of sustainability.
          </p>
        </div>





        <div className='section'>
          <h3>Solution</h3>
          <p className="leading-loose">
            By enabling small to medium-sized medical practices to reprocess reusable instruments such as scissors, tweezers, and forceps, the modClave effectively addresses the pain points identified during the research phase. It alleviates the financial burden associated with traditional autoclaves, which have forced clinics to rely on single-use instruments that contribute to waste stream.
          </p>
        </div>




        <Image
          alt="modclave module closeup with instruments shown"
          src={module_closeup}
          sizes="(min-width: 808px) 50vw, 100vw"
          className='off-width'
          placeholder="blur"
        />


        <div className='section'>
          <h3>Outcome</h3>
          <p className="leading-loose">
            With its potential to promote sustainable practices across various facets of the medical industry, the modClave represents a significant advancement in addressing waste mismanagement. This project has not only enhanced my skills as a graduate of industrial design has emphasised for myself the importance of addressing waste during product development and understanding the need to know explicitly what my users problems are.
          </p>
        </div>



        <div className="section">
          <h3>Read More</h3>
          <Link id="file_link" href='https://www.dropbox.com/s/ks2ap17jhnmhhqg/modClave%20Designed%20Document%20with%20Justification%20Chapter%201-11-2022.pdf?dl=0' target="_blank" className="bg-gray-100 flex justify-between items-center hover:bg-gray-200 px-6 py-4">
            <span className="text-4xl">
              📁
            </span>
            <p className="text-lg xl:text-2xl">
              Read the full thesis
            </p>
          </Link>

          <Link id="file_link" href='https://www.youtube.com/watch?v=l13PFV3bYVM' target="_blank" className="bg-gray-100 flex justify-between items-center hover:bg-gray-200 px-6 py-4">
            <span className="text-4xl">
              📺
            </span>
            <p className="text-lg xl:text-2xl">
              Watch the introduction video
            </p>
          </Link>



          <Link id="file_link" href='https://www.dropbox.com/s/hz9wytv6cwmpg6a/Final%20DDR%20Pages%20-%20Isaac%20Bonora%20-%2010-11-22.pdf?dl=0' target="_blank" className="bg-gray-100 flex justify-between items-center hover:bg-gray-200 px-6 py-4">
            <span className="text-4xl">
              📒
            </span>
            <p className="text-lg xl:text-2xl">
              Explore the DDR
            </p>
          </Link>
        </div>

      </div>
    </main>
  );
}
