import Image from "next/image";
import Link from "next/link";

import modclave from "@/public/projects/modclaveHero.jpg";
import module_closeup from "./module_closeup.jpg";
import autoclave_requirements from "./autoclave_requirements.png";
import instruments_stockphoto from "./ibrahim-boran-pV5arhEZHiA-unsplash.jpg";

import Section from "@/components/project/section";
import InlineSection from "@/components/project/InlineSection";
import ProjectInfo from "@/components/project/ProjectInfo";
import ExternalLink from "@/components/project/ExternalLink";

export default function Home() {
  return (
    <div className="project-body">
      <Section>
        <h1>modClave: Store & Sterilise</h1>
        <p className="lead">
          An affordable and compact sterilisation device that addresses waste
          mismanagement in healthcare by enabling clinics to reprocess
          instruments, promoting sustainability and emphasizing the importance
          of waste reduction during product development.
        </p>

        <ProjectInfo
          clientName="Queensland University of Technology"
          datePeriod="2022"
          bodyText="This project was completed over 12-months in the final year of my
          Industrial Design degree as my disertation project. The projects
          outcome incluced a reserach thesis and a developed product based on
          the reserach completed in the first 6 months of the project."
        />
      </Section>

      <Image
        alt="hero image of the modclave"
        src={modclave}
        sizes="(min-width: 808px) 50vw, 100vw"
        className="off-width"
        placeholder="blur"
      />

      <Section>
        <h3>Introduction</h3>
        <p>
          The modClave, a module-based steam sterilisation desktop appliance, is
          a groundbreaking solution that addresses the issues of waste
          mismanagement and sustainability in the healthcare industry. Developed
          through extensive research involving healthcare professionals in
          south-east Queensland, the modClave tackles the prevalent problem of
          excessive waste generated by poor waste practices.
        </p>
      </Section>

      <Section className="items-center">
        <Image
          alt="hero image of the modclave"
          src={instruments_stockphoto}
          sizes="(min-width: 808px) 50vw, 100vw"
          placeholder="blur"
        />
        <p className="caption">
          Example of single-use instruments that are often used once and
          disposed of in medical practices. (
          <Link href="https://unsplash.com/photos/pV5arhEZHiA" target="_blank">
            source: Ibrahim Boran, Unsplash
          </Link>
          )
        </p>
      </Section>

      <Section>
        <h3>Problem</h3>
        <p>
          While healthcare professionals express their intentions to be
          sustainable, the reality is that the industry heavily relies on a
          pay-per-use model, resulting in the disposal of large volumes of
          single-use instruments. This wasteful approach is particularly
          prominent in smaller practices, where sustainable alternatives are
          deemed too expensive and time-consuming, exacerbating the issue of
          excess waste.
        </p>
      </Section>

      <InlineSection>
        <div className="flex flex-col items-center">
          <Image
            alt="example of a room layout with a traditional autoclave"
            src={autoclave_requirements}
            sizes="(min-width: 800px) 50vw, 100vw"
            placeholder="blur"
          />
          <p className=" text-xs font-light text-slate-500 max-w-md leading-loose">
            Extracted from Infection prevention and control standards: for
            general practices and other office-based and community-based
            practices (RACGP, 2014)
          </p>
        </div>
        <p>
          Traditionally, autoclaves have been the gold standard for
          sterilisation in the medical industry. However, their high cost, space
          requirements, and inefficiency for smaller practices have limited
          their accessibility and effectiveness. The modClave revolutionises
          waste management practices by providing an affordable and compact
          solution for clinics that are currently priced out of sustainability.
        </p>
      </InlineSection>

      <Section>
        <h3>Solution</h3>
        <p>
          By enabling small to medium-sized medical practices to reprocess
          reusable instruments such as scissors, tweezers, and forceps, the
          modClave effectively addresses the pain points identified during the
          research phase. It alleviates the financial burden associated with
          traditional autoclaves, which have forced clinics to rely on
          single-use instruments that contribute to waste stream.
        </p>
      </Section>

      <Image
        alt="modclave module closeup with instruments shown"
        src={module_closeup}
        sizes="(min-width: 808px) 50vw, 100vw"
        className="off-width"
        placeholder="blur"
      />

      <Section>
        <h3>Outcome</h3>
        <p>
          With its potential to promote sustainable practices across various
          facets of the medical industry, the modClave represents a significant
          advancement in addressing waste mismanagement. This project has not
          only enhanced my skills as a graduate of industrial design has
          emphasised for myself the importance of addressing waste during
          product development and understanding the need to know explicitly what
          my users problems are.
        </p>
      </Section>

      <Section>
        <h3>Read More</h3>
        <ExternalLink
          href="https://www.dropbox.com/s/ks2ap17jhnmhhqg/modClave%20Designed%20Document%20with%20Justification%20Chapter%201-11-2022.pdf?dl=0"
          emoji="📁"
          description="Read the full thesis"
        />
        <ExternalLink
          href="https://www.dropbox.com/s/hz9wytv6cwmpg6a/Final%20DDR%20Pages%20-%20Isaac%20Bonora%20-%2010-11-22.pdf?dl=0"
          emoji="📺"
          description="Watch the introduction video"
        />
        <ExternalLink
          href="https://www.dropbox.com/s/hz9wytv6cwmpg6a/Final%20DDR%20Pages%20-%20Isaac%20Bonora%20-%2010-11-22.pdf?dl=0"
          emoji="📒"
          description="Explore the DDR"
        />
      </Section>
    </div>
  );
}
